#! /bin/bash
# Create new
sudo fallocate -l 6G /swapfile

# Set proper permissions and format
sudo chmod 600 /swapfile
sudo mkswap /swapfile

# Enable the new swap
sudo swapon /swapfile

# Optional: make permanent
# echo '/swapfile                                 swap           swap    defaults   0 0' | sudo tee -a /etc/fstab
# Or
# echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
